version: '3.4'
services:
  # Postgresql database
  text2lex_postgres:
    container_name: text2lex_postgres
    image: postgres:11
    volumes:
      - /var/lib/postgresql/data/text2lex:/var/lib/postgresql/data

  # Redis database
  text2lex_redis:
    container_name: text2lex_redis
    image: redis:alpine
    volumes:
      - /var/lib/redis/6379/text2lex/:/data

  # Flask API
  text2lex_api:
    container_name: text2lex_api
    build:
      context: ../backend/api
      dockerfile: Dockerfile
    volumes:
      - ../backend/api/src:/opt/text2lex/api/src
      - ../shared:/opt/text2lex/shared
      - /var/log/text2lex/api:/var/log/text2lex

  # NLTK with Redis RQ service that runs scheduled tasks
  text2lex_nlp:
    container_name: text2lex_nlp
    build:
      context: ../backend/nlp
      dockerfile: Dockerfile
    environment:
      - PATH=$PATH:/opt/text2lex/nlp/src
    volumes:
      - ../backend/nlp/src:/opt/text2lex/nlp/src
      - ../shared:/opt/text2lex/shared
      - /var/log/text2lex/nlp:/var/log/text2lex

  # RQ Scheduler daemon to delay and schedule tasks scrapes
  text2lex_scheduler:
    container_name: text2lex_scheduler
    build:
      context: ../rqscheduler
      dockerfile: Dockerfile
    depends_on:
      - text2lex_redis
      - text2lex_nlp

  # AngularJS UI
  text2lex_frontend:
    container_name: text2lex_frontend
    volumes:
      - ../frontend/src:/opt/text2lex/frontend/src
      - /var/log/text2lex/frontend:/var/log/text2lex
